services:
  - type: web
    name: n8n-free
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    region: oregon
    envVars:
      - key: N8N_BASIC_AUTH_ACTIVE
        value: "true"
      - key: N8N_BASIC_AUTH_USER
        value: "eruns"
      - key: N8N_BASIC_AUTH_PASSWORD
        value: "eddy4545"
      - key: WEBHOOK_TUNNEL_URL
        value: "https://n8n-free.onrender.com"
      - key: N8N_HOST
        value: "0.0.0.0"
      - key: N8N_PORT
        value: "5678"
      - key: N8N_EDITOR_BASE_URL
        value: "https://n8n-free.onrender.com"
